// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonalQuant.Infrastructure.Persistence;

#nullable disable

namespace PersonalQuant.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PersonalQuantDbContext))]
    [Migration("20260814074113_InstrumentMaster")]
    partial class InstrumentMaster
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("quant")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PersonalQuant.Domain.Exchanges.Exchange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Mic")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("mic");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_exchanges");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_exchanges_code");

                    b.ToTable("exchanges", "quant");
                });

            modelBuilder.Entity("PersonalQuant.Domain.Instruments.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AssetType")
                        .HasColumnType("integer")
                        .HasColumnName("asset_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<DateOnly?>("DelistedOn")
                        .HasColumnType("date")
                        .HasColumnName("delisted_on");

                    b.Property<Guid>("ExchangeId")
                        .HasColumnType("uuid")
                        .HasColumnName("exchange_id");

                    b.Property<DateOnly?>("ListedOn")
                        .HasColumnType("date")
                        .HasColumnName("listed_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ticker");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_instruments");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_instruments_status");

                    b.HasIndex(new[] { "ExchangeId", "Ticker" }, "ActiveTickerPerExchange")
                        .IsUnique()
                        .HasDatabaseName("ux_instruments_active_ticker_per_exchange")
                        .HasFilter("status <> 3");

                    b.HasIndex(new[] { "ExchangeId", "Ticker" }, "TickerPerExchange")
                        .HasDatabaseName("ix_instruments_ticker_per_exchange");

                    b.ToTable("instruments", "quant");
                });

            modelBuilder.Entity("PersonalQuant.Domain.Instruments.Instrument", b =>
                {
                    b.HasOne("PersonalQuant.Domain.Exchanges.Exchange", null)
                        .WithMany()
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_instruments_exchange");
                });
#pragma warning restore 612, 618
        }
    }
}
