// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PersonalQuant.Infrastructure.Persistence;

#nullable disable

namespace PersonalQuant.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PersonalQuantDbContext))]
    [Migration("20260826122325_MarketDataIngestion")]
    partial class MarketDataIngestion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("quant")
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PersonalQuant.Domain.Classification.Industry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("SectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sector_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_industries");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_industries_code");

                    b.HasIndex("SectorId")
                        .HasDatabaseName("ix_industries_sector");

                    b.ToTable("industries", "quant");
                });

            modelBuilder.Entity("PersonalQuant.Domain.Classification.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_sectors");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_sectors_code");

                    b.ToTable("sectors", "quant");
                });

            modelBuilder.Entity("PersonalQuant.Domain.Exchanges.Exchange", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Mic")
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)")
                        .HasColumnName("mic");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("time_zone_id");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_exchanges");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_exchanges_code");

                    b.ToTable("exchanges", "quant");
                });

            modelBuilder.Entity("PersonalQuant.Domain.Instruments.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AssetType")
                        .HasColumnType("integer")
                        .HasColumnName("asset_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character(3)")
                        .HasColumnName("currency")
                        .IsFixedLength();

                    b.Property<DateOnly?>("DelistedOn")
                        .HasColumnType("date")
                        .HasColumnName("delisted_on");

                    b.Property<Guid>("ExchangeId")
                        .HasColumnType("uuid")
                        .HasColumnName("exchange_id");

                    b.Property<Guid?>("IndustryId")
                        .HasColumnType("uuid")
                        .HasColumnName("industry_id");

                    b.Property<DateOnly?>("ListedOn")
                        .HasColumnType("date")
                        .HasColumnName("listed_on");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("name");

                    b.Property<string>("SearchName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("search_name");

                    b.Property<string>("SearchTicker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("search_ticker");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ticker");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_instruments");

                    b.HasIndex("IndustryId")
                        .HasDatabaseName("ix_instruments_industry")
                        .HasFilter("industry_id IS NOT NULL");

                    b.HasIndex("SearchName")
                        .HasDatabaseName("ix_instruments_search_name");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchName"), new[] { "varchar_pattern_ops" });

                    b.HasIndex("SearchTicker")
                        .HasDatabaseName("ix_instruments_search_ticker");

                    NpgsqlIndexBuilderExtensions.HasOperators(b.HasIndex("SearchTicker"), new[] { "varchar_pattern_ops" });

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_instruments_status");

                    b.HasIndex(new[] { "ExchangeId", "Ticker" }, "ActiveTickerPerExchange")
                        .IsUnique()
                        .HasDatabaseName("ux_instruments_active_ticker_per_exchange")
                        .HasFilter("status <> 3");

                    b.HasIndex(new[] { "ExchangeId", "Ticker" }, "TickerPerExchange")
                        .HasDatabaseName("ix_instruments_ticker_per_exchange");

                    b.ToTable("instruments", "quant");
                });

            modelBuilder.Entity("PersonalQuant.Domain.MarketData.IngestionCheckpoint", b =>
                {
                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<int>("Interval")
                        .HasColumnType("integer")
                        .HasColumnName("interval_minutes");

                    b.Property<string>("Source")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("LastBarOpenedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_bar_opened_at_utc");

                    b.Property<DateTimeOffset>("LastSucceededAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_succeeded_at_utc");

                    b.HasKey("InstrumentId", "Interval", "Source")
                        .HasName("pk_ingestion_checkpoints");

                    b.ToTable("ingestion_checkpoints", "quant");
                });

            modelBuilder.Entity("PersonalQuant.Domain.MarketData.IngestionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempts")
                        .HasColumnType("integer")
                        .HasColumnName("attempts");

                    b.Property<int>("BarsAccepted")
                        .HasColumnType("integer")
                        .HasColumnName("bars_accepted");

                    b.Property<int>("BarsFetched")
                        .HasColumnType("integer")
                        .HasColumnName("bars_fetched");

                    b.Property<int>("BarsRejected")
                        .HasColumnType("integer")
                        .HasColumnName("bars_rejected");

                    b.Property<int>("BarsRevised")
                        .HasColumnType("integer")
                        .HasColumnName("bars_revised");

                    b.Property<int>("BarsStored")
                        .HasColumnType("integer")
                        .HasColumnName("bars_stored");

                    b.Property<DateTimeOffset?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at_utc");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("failure_reason");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<int>("Interval")
                        .HasColumnType("integer")
                        .HasColumnName("interval_minutes");

                    b.Property<int>("Outcome")
                        .HasColumnType("integer")
                        .HasColumnName("outcome");

                    b.Property<Guid?>("RawBatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("raw_batch_id");

                    b.Property<DateTimeOffset>("RequestedFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_from_utc");

                    b.Property<DateTimeOffset>("RequestedToUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_to_utc");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<DateTimeOffset>("StartedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at_utc");

                    b.HasKey("Id")
                        .HasName("pk_ingestion_runs");

                    b.HasIndex("Outcome", "StartedAtUtc")
                        .HasDatabaseName("ix_ingestion_runs_outcome");

                    b.HasIndex("InstrumentId", "Interval", "StartedAtUtc")
                        .HasDatabaseName("ix_ingestion_runs_instrument_period");

                    b.ToTable("ingestion_runs", "quant");
                });

            modelBuilder.Entity("PersonalQuant.Domain.MarketData.OhlcvBar", b =>
                {
                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<int>("Interval")
                        .HasColumnType("integer")
                        .HasColumnName("interval_minutes");

                    b.Property<DateTimeOffset>("OpenedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at_utc");

                    b.Property<decimal>("Close")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("close");

                    b.Property<decimal>("High")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("high");

                    b.Property<DateTimeOffset>("IngestedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ingested_at_utc");

                    b.Property<decimal>("Low")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("low");

                    b.Property<decimal>("Open")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("open");

                    b.Property<DateTimeOffset?>("RevisedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("revised_at_utc");

                    b.Property<int>("Revision")
                        .HasColumnType("integer")
                        .HasColumnName("revision");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.Property<decimal?>("Turnover")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("turnover");

                    b.Property<long>("Volume")
                        .HasColumnType("bigint")
                        .HasColumnName("volume");

                    b.HasKey("InstrumentId", "Interval", "OpenedAtUtc")
                        .HasName("pk_bars");

                    b.HasIndex("Interval", "OpenedAtUtc")
                        .HasDatabaseName("ix_bars_interval_period");

                    b.ToTable("bars", "quant");
                });

            modelBuilder.Entity("PersonalQuant.Domain.MarketData.RawMarketDataBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Checksum")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character(64)")
                        .HasColumnName("checksum")
                        .IsFixedLength();

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("FetchedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at_utc");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<int>("Interval")
                        .HasColumnType("integer")
                        .HasColumnName("interval_minutes");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("RequestedFromUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_from_utc");

                    b.Property<DateTimeOffset>("RequestedToUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_to_utc");

                    b.Property<int>("SizeBytes")
                        .HasColumnType("integer")
                        .HasColumnName("size_bytes");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_market_data_raw_batches");

                    b.HasIndex("InstrumentId", "Interval", "FetchedAtUtc")
                        .HasDatabaseName("ix_market_data_raw_batches_instrument_period");

                    b.ToTable("market_data_raw_batches", "quant");
                });

            modelBuilder.Entity("PersonalQuant.Domain.Classification.Industry", b =>
                {
                    b.HasOne("PersonalQuant.Domain.Classification.Sector", null)
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_industries_sector");
                });

            modelBuilder.Entity("PersonalQuant.Domain.Instruments.Instrument", b =>
                {
                    b.HasOne("PersonalQuant.Domain.Exchanges.Exchange", null)
                        .WithMany()
                        .HasForeignKey("ExchangeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_instruments_exchange");

                    b.HasOne("PersonalQuant.Domain.Classification.Industry", null)
                        .WithMany()
                        .HasForeignKey("IndustryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_instruments_industry");
                });

            modelBuilder.Entity("PersonalQuant.Domain.MarketData.IngestionCheckpoint", b =>
                {
                    b.HasOne("PersonalQuant.Domain.Instruments.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ingestion_checkpoints_instrument");
                });

            modelBuilder.Entity("PersonalQuant.Domain.MarketData.IngestionRun", b =>
                {
                    b.HasOne("PersonalQuant.Domain.Instruments.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ingestion_runs_instrument");
                });

            modelBuilder.Entity("PersonalQuant.Domain.MarketData.OhlcvBar", b =>
                {
                    b.HasOne("PersonalQuant.Domain.Instruments.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_bars_instrument");
                });

            modelBuilder.Entity("PersonalQuant.Domain.MarketData.RawMarketDataBatch", b =>
                {
                    b.HasOne("PersonalQuant.Domain.Instruments.Instrument", null)
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_market_data_raw_batches_instrument");
                });
#pragma warning restore 612, 618
        }
    }
}
